name: Practice0
version: 1.0.0
main: fr.acth2.p0pp.Main

api-version: 1.13
author: AcTh2
description: Practice0 Plugin
maintainer: AcTh2
authors: [AcTh2]

commands:
  duel:
    description: Commande pour les duels en practice
    usage: /duel <joueur>